### ISSUE TITLE
Textures missing

### ISSUE THREAD

**Issue by jaywillscott** [atang152/crappyBall-cx#3]
When attempting to run the game there is an error:
panic: texture "textures\texture.png" not found on disk: open textures  exture.png: The filename, directory name, or volume label syntax is incorrect.

Looks like the textures folder isn't included in the repo.

**Comment by atang152** [comment]
Hi redcurse. Thanks for bringing it up. My gitignore ignored png files before. I added the textures folder into the repo. It should work now. Cheers.
